# Generated by Django 4.1.3 on 2022-11-22 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("signlanguage", "0007_delete_aimodel"),
    ]

    operations = [
        migrations.CreateModel(
            name="AI_model",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("model", models.FileField(upload_to="")),
                ("version", models.CharField(max_length=200)),
                ("use_type", models.BooleanField(default=False)),
                ("pub_date", models.DateTimeField(verbose_name="date published")),
            ],
        ),
    ]
