# Generated by Django 4.1.3 on 2022-11-22 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("signlanguage", "0008_ai_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="ai_model",
            name="predict_cnt",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="ai_model",
            name="total_cnt",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="ai_model",
            name="model",
            field=models.FileField(upload_to="model/"),
        ),
        migrations.AlterField(
            model_name="result",
            name="image",
            field=models.ImageField(blank=True, upload_to="img/%Y/%m/"),
        ),
    ]
